import { Meeting, MeetingTypes } from './type';

export const dummy: Array<Meeting> = [
  {
    type: MeetingTypes.Team,
    title: 'Team Meeting Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Business,
    title: 'Business Trip/Outside Work Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Personal,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
  },
  {
    type: MeetingTypes.Team,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Business,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: 'Hall A',
    people: 'Andreas',
  },
  {
    type: MeetingTypes.Business,
    title: 'Business Trip/Outside Work Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Personal,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Team,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Personal,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
    people: 'Andreas and 14 others',
  },
  {
    type: MeetingTypes.Personal,
    title: 'Personal Schedule Title',
    date: 'Wed, Aug 16th 2023',
    time: '14:00 ~ 17:00',
    place: '7F Conference Room A',
  },
];
